# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c36e0166eed2ca769f2c15827426a93896b5871b5cd1c659822751203e457d66230c70bf1b8b9b26af19a1aa7b0d8ba2359c46bdef8328f97f6694ff8161bcf

test:
  secret_key_base: 69f1a33a06db25e6f36e0728bccbe5ed061f2f3baad2868316ba1ef389929c506b1a0bbcf6972d21ee62f64eaa23f3f5d532382e2bdef6c4f4f32fac07cfee3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
